name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t user-management-microservice .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag user-management-microservice ${{ secrets.DOCKER_USERNAME }}/user-management-microservice:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/user-management-microservice:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1.2.1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f user-management-deployment.yaml -f user-management-service.yaml
